-- MySQL Script generated by MySQL Workbench
-- Чт 06 фев 2025 16:56:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema avto_is28
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema avto_is28
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avto_is28` ;
USE `avto_is28` ;

-- -----------------------------------------------------
-- Table `avto_is28`.`kyzov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_is28`.`kyzov` (
  `id_k` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_k`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_is28`.`marka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_is28`.`marka` (
  `id_m` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_k` INT NOT NULL,
  PRIMARY KEY (`id_m`),
  INDEX `fk_marka_kyzov_idx` (`id_k` ASC) VISIBLE,
  CONSTRAINT `fk_marka_kyzov`
    FOREIGN KEY (`id_k`)
    REFERENCES `avto_is28`.`kyzov` (`id_k`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_is28`.`proizvoditel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_is28`.`proizvoditel` (
  `id_p` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `telefon` CHAR(11) NOT NULL,
  PRIMARY KEY (`id_p`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_is28`.`avto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_is28`.`avto` (
  `id_a` INT NOT NULL AUTO_INCREMENT,
  `vin_number` VARCHAR(15) NOT NULL,
  `id_m` INT NOT NULL,
  `id_p` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_a`),
  UNIQUE INDEX `vin_number_UNIQUE` (`vin_number` ASC) VISIBLE,
  INDEX `fk_avto_marka1_idx` (`id_m` ASC) VISIBLE,
  INDEX `fk_avto_proizvoditel1_idx` (`id_p` ASC) VISIBLE,
  CONSTRAINT `fk_avto_marka1`
    FOREIGN KEY (`id_m`)
    REFERENCES `avto_is28`.`marka` (`id_m`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avto_proizvoditel1`
    FOREIGN KEY (`id_p`)
    REFERENCES `avto_is28`.`proizvoditel` (`id_p`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_is28`.`postavjiki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_is28`.`postavjiki` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `telefon` CHAR(11) NOT NULL,
  PRIMARY KEY (`id_post`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_is28`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_is28`.`city` (
  `id_c` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_c`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_is28`.`street`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_is28`.`street` (
  `id_st` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_st`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_is28`.`adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_is28`.`adress` (
  `id_a` INT NOT NULL AUTO_INCREMENT,
  `house` VARCHAR(5) NOT NULL,
  `korpus` VARCHAR(3) NULL,
  `index_p` CHAR(6) NOT NULL,
  `id_c` INT NOT NULL,
  `id_st` INT NOT NULL,
  `id_post` INT NOT NULL,
  PRIMARY KEY (`id_a`),
  INDEX `fk_adress_city1_idx` (`id_c` ASC) VISIBLE,
  INDEX `fk_adress_street1_idx` (`id_st` ASC) VISIBLE,
  INDEX `fk_adress_postavjiki1_idx` (`id_post` ASC) VISIBLE,
  CONSTRAINT `fk_adress_city1`
    FOREIGN KEY (`id_c`)
    REFERENCES `avto_is28`.`city` (`id_c`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adress_street1`
    FOREIGN KEY (`id_st`)
    REFERENCES `avto_is28`.`street` (`id_st`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adress_postavjiki1`
    FOREIGN KEY (`id_post`)
    REFERENCES `avto_is28`.`postavjiki` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_is28`.`contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_is28`.`contracts` (
  `id_contr` INT NOT NULL AUTO_INCREMENT,
  `date_contr` DATE NOT NULL,
  `number` VARCHAR(10) NOT NULL,
  `date_d` DATE NOT NULL,
  `comment` VARCHAR(100) NOT NULL,
  `id_post` INT NOT NULL,
  PRIMARY KEY (`id_contr`),
  INDEX `fk_contracts_postavjiki1_idx` (`id_post` ASC) VISIBLE,
  CONSTRAINT `fk_contracts_postavjiki1`
    FOREIGN KEY (`id_post`)
    REFERENCES `avto_is28`.`postavjiki` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_is28`.`postavki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_is28`.`postavki` (
  `id_postavki` INT NOT NULL AUTO_INCREMENT,
  `date_postavki` DATE NOT NULL,
  `number` VARCHAR(5) NOT NULL,
  `date_d` DATE NOT NULL,
  `id_contr` INT NOT NULL,
  PRIMARY KEY (`id_postavki`),
  INDEX `fk_postavki_contracts1_idx` (`id_contr` ASC) VISIBLE,
  CONSTRAINT `fk_postavki_contracts1`
    FOREIGN KEY (`id_contr`)
    REFERENCES `avto_is28`.`contracts` (`id_contr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_is28`.`avto_has_postavki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_is28`.`avto_has_postavki` (
  `id_postavki` INT NOT NULL,
  `id_a` INT NOT NULL,
  `kol` INT NOT NULL,
  PRIMARY KEY (`id_postavki`, `id_a`),
  INDEX `fk_avto_has_postavki_postavki1_idx` (`id_postavki` ASC) VISIBLE,
  INDEX `fk_avto_has_postavki_avto1_idx` (`id_a` ASC) VISIBLE,
  CONSTRAINT `fk_avto_has_postavki_avto1`
    FOREIGN KEY (`id_a`)
    REFERENCES `avto_is28`.`avto` (`id_a`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avto_has_postavki_postavki1`
    FOREIGN KEY (`id_postavki`)
    REFERENCES `avto_is28`.`postavki` (`id_postavki`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
