-- MySQL Script generated by MySQL Workbench
-- Чт 23 янв 2025 19:23:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema avto_IS28
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema avto_IS28
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avto_IS28` ;
USE `avto_IS28` ;

-- -----------------------------------------------------
-- Table `avto_IS28`.`kyzov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_IS28`.`kyzov` (
  `id_kyzov` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_kyzov`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_IS28`.`table_mark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_IS28`.`table_mark` (
  `id_mark` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_kyzov` INT NOT NULL,
  PRIMARY KEY (`id_mark`),
  INDEX `fk_table_mark_kyzov_idx` (`id_kyzov` ASC) VISIBLE,
  CONSTRAINT `fk_table_mark_kyzov`
    FOREIGN KEY (`id_kyzov`)
    REFERENCES `avto_IS28`.`kyzov` (`id_kyzov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_IS28`.`proizvoditel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_IS28`.`proizvoditel` (
  `id_proizvoditel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_proizvoditel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_IS28`.`avto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_IS28`.`avto` (
  `id_avto` INT NOT NULL AUTO_INCREMENT,
  `vin_number` VARCHAR(15) NOT NULL,
  `telephone` VARCHAR(45) NULL,
  `id_mark` INT NOT NULL,
  `id_proizvoditel` INT NOT NULL,
  PRIMARY KEY (`id_avto`),
  UNIQUE INDEX `vin_number_UNIQUE` (`vin_number` ASC) VISIBLE,
  INDEX `fk_avto_table_mark1_idx` (`id_mark` ASC) VISIBLE,
  INDEX `fk_avto_proizvoditel1_idx` (`id_proizvoditel` ASC) VISIBLE,
  CONSTRAINT `fk_avto_table_mark1`
    FOREIGN KEY (`id_mark`)
    REFERENCES `avto_IS28`.`table_mark` (`id_mark`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avto_proizvoditel1`
    FOREIGN KEY (`id_proizvoditel`)
    REFERENCES `avto_IS28`.`proizvoditel` (`id_proizvoditel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avto_IS28`.`postavshiki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avto_IS28`.`postavshiki` (
  `id_postavshiki` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `telefon` CHAR(11) NOT NULL,
  PRIMARY KEY (`id_postavshiki`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
